import type { Question } from "./types";

/**
 * 72 題原創繁體中文題庫。
 * 每個維度 12 題：至少 3 題反向計分（direction: -1）、
 * 2 組語意配對題（pairId）、3 題以上情境式題目。
 *
 * direction = 1：同意越多，越偏向維度第一個字母（E/S/T/J/A/H）
 * direction = -1：同意越多，越偏向維度第二個字母（I/N/F/P/O/C）
 */
export const QUESTIONS: Question[] = [
  // ───────────────────────── E / I：能量來源 ─────────────────────────
  {
    id: "EI01",
    text: "連續參加幾場聚會之後，我常覺得精神反而更好。",
    dimension: "EI",
    direction: 1,
    weight: 1,
    pairId: "EI-p1",
    category: "daily",
  },
  {
    id: "EI02",
    text: "熱鬧的活動結束後，我需要一段獨處時間才能恢復精力。",
    dimension: "EI",
    direction: -1,
    weight: 1,
    pairId: "EI-p1",
    category: "daily",
  },
  {
    id: "EI03",
    text: "開會或討論時，我傾向邊說邊整理想法，而不是想完才開口。",
    dimension: "EI",
    direction: 1,
    weight: 1,
    pairId: "EI-p2",
    category: "work",
  },
  {
    id: "EI04",
    text: "在會議中，我通常會先在心裡把想法整理好，才會開口。",
    dimension: "EI",
    direction: -1,
    weight: 1,
    pairId: "EI-p2",
    category: "work",
  },
  {
    id: "EI05",
    text: "在陌生的場合，我通常會主動開啟話題。",
    dimension: "EI",
    direction: 1,
    weight: 1,
    category: "relationship",
  },
  {
    id: "EI06",
    text: "認識新朋友時，我比較希望對方先開口。",
    dimension: "EI",
    direction: -1,
    weight: 1,
    category: "relationship",
  },
  {
    id: "EI07",
    text: "壓力大的時候，找人聊一聊通常比自己消化更有幫助。",
    dimension: "EI",
    direction: 1,
    weight: 1,
    category: "stress",
  },
  {
    id: "EI08",
    text: "遇到煩心的事，我傾向先自己安靜想清楚，再決定要不要說。",
    dimension: "EI",
    direction: -1,
    weight: 1,
    category: "stress",
  },
  {
    id: "EI09",
    text: "小組討論比獨自研讀更能幫助我理解新的內容。",
    dimension: "EI",
    direction: 1,
    weight: 1,
    category: "learning",
  },
  {
    id: "EI10",
    text: "週末如果完全沒有和人碰面的安排，我會覺得少了點什麼。",
    dimension: "EI",
    direction: 1,
    weight: 1,
    category: "daily",
  },
  {
    id: "EI11",
    text: "一整天沒有和任何人說話，對我來說也可以很自在。",
    dimension: "EI",
    direction: -1,
    weight: 1,
    category: "daily",
  },
  {
    id: "EI12",
    text: "思考重要決定時，我喜歡找幾個人一起討論，越談越清楚。",
    dimension: "EI",
    direction: 1,
    weight: 1,
    category: "decision",
  },

  // ───────────────────────── S / N：資訊接收 ─────────────────────────
  {
    id: "SN01",
    text: "接到新任務時，我最先想知道的是具體步驟與明確要求。",
    dimension: "SN",
    direction: 1,
    weight: 1,
    pairId: "SN-p1",
    category: "work",
  },
  {
    id: "SN02",
    text: "接到新任務時，我最先想到的是它背後的可能性與延伸空間。",
    dimension: "SN",
    direction: -1,
    weight: 1,
    pairId: "SN-p1",
    category: "work",
  },
  {
    id: "SN03",
    text: "學新東西時，先看實際範例對我最有幫助。",
    dimension: "SN",
    direction: 1,
    weight: 1,
    pairId: "SN-p2",
    category: "learning",
  },
  {
    id: "SN04",
    text: "學新東西時，我喜歡先掌握整體概念，細節之後再補。",
    dimension: "SN",
    direction: -1,
    weight: 1,
    pairId: "SN-p2",
    category: "learning",
  },
  {
    id: "SN05",
    text: "描述一件事情時，我習慣照實際發生的順序，把細節講清楚。",
    dimension: "SN",
    direction: 1,
    weight: 1,
    category: "daily",
  },
  {
    id: "SN06",
    text: "聊天時，我常常從一個話題聯想到完全不同的想法。",
    dimension: "SN",
    direction: -1,
    weight: 1,
    category: "daily",
  },
  {
    id: "SN07",
    text: "做判斷時，我更相信已經驗證過的做法，而不是新奇的點子。",
    dimension: "SN",
    direction: 1,
    weight: 1,
    category: "decision",
  },
  {
    id: "SN08",
    text: "我常會想像各種「如果……會怎樣」的情境，即使不一定會發生。",
    dimension: "SN",
    direction: -1,
    weight: 1,
    category: "daily",
  },
  {
    id: "SN09",
    text: "我擅長注意到文件或成品裡的小錯誤與不一致。",
    dimension: "SN",
    direction: 1,
    weight: 1,
    category: "work",
  },
  {
    id: "SN10",
    text: "比起眼前的現況，我更常思考事情未來可能的樣子。",
    dimension: "SN",
    direction: -1,
    weight: 1,
    category: "decision",
  },
  {
    id: "SN11",
    text: "情況混亂時，我會先確認手邊已經確定的事實，一步一步處理。",
    dimension: "SN",
    direction: 1,
    weight: 1,
    category: "stress",
  },
  {
    id: "SN12",
    text: "情況混亂時，我會先退一步，找出整體的模式或原因。",
    dimension: "SN",
    direction: -1,
    weight: 1,
    category: "stress",
  },

  // ───────────────────────── T / F：決策依據 ─────────────────────────
  {
    id: "TF01",
    text: "做重要決定時，我會先把個人感受放到一邊，專注分析利弊。",
    dimension: "TF",
    direction: 1,
    weight: 1,
    pairId: "TF-p1",
    category: "decision",
  },
  {
    id: "TF02",
    text: "做重要決定時，我會先考慮這對相關的人會造成什麼影響。",
    dimension: "TF",
    direction: -1,
    weight: 1,
    pairId: "TF-p1",
    category: "decision",
  },
  {
    id: "TF03",
    text: "同事的提案有明顯漏洞時，我會直接指出問題，即使氣氛會變得嚴肅。",
    dimension: "TF",
    direction: 1,
    weight: 1,
    pairId: "TF-p2",
    category: "work",
  },
  {
    id: "TF04",
    text: "給別人回饋之前，我會先想好怎麼說才不會讓對方難受。",
    dimension: "TF",
    direction: -1,
    weight: 1,
    pairId: "TF-p2",
    category: "work",
  },
  {
    id: "TF05",
    text: "朋友向我訴苦時，我的第一反應通常是幫忙分析問題和解法。",
    dimension: "TF",
    direction: 1,
    weight: 1,
    category: "relationship",
  },
  {
    id: "TF06",
    text: "朋友向我訴苦時，我覺得先陪伴和理解，比急著給建議更重要。",
    dimension: "TF",
    direction: -1,
    weight: 1,
    category: "relationship",
  },
  {
    id: "TF07",
    text: "評估方案時，一致的標準比個別情況的特殊性更重要。",
    dimension: "TF",
    direction: 1,
    weight: 1,
    category: "work",
  },
  {
    id: "TF08",
    text: "看電影或讀故事時，我很容易被角色的心情牽動。",
    dimension: "TF",
    direction: -1,
    weight: 1,
    category: "daily",
  },
  {
    id: "TF09",
    text: "意見衝突時，我在意的是哪個說法更站得住腳，而不是誰的情緒比較強。",
    dimension: "TF",
    direction: 1,
    weight: 1,
    category: "stress",
  },
  {
    id: "TF10",
    text: "團隊氣氛緊張時，我會先想辦法緩和關係，再處理事情本身。",
    dimension: "TF",
    direction: -1,
    weight: 1,
    category: "stress",
  },
  {
    id: "TF11",
    text: "就算結論不討喜，我還是傾向照邏輯得出的答案走。",
    dimension: "TF",
    direction: 1,
    weight: 1,
    category: "decision",
  },
  {
    id: "TF12",
    text: "做選擇時，維持關係的和諧對我來說是重要的考量。",
    dimension: "TF",
    direction: -1,
    weight: 1,
    category: "relationship",
  },

  // ───────────────────────── J / P：生活節奏 ─────────────────────────
  {
    id: "JP01",
    text: "出遠門之前，我會把行程和住宿大致安排好才安心。",
    dimension: "JP",
    direction: 1,
    weight: 1,
    pairId: "JP-p1",
    category: "daily",
  },
  {
    id: "JP02",
    text: "旅行時，我喜歡到了當地再看心情決定要做什麼。",
    dimension: "JP",
    direction: -1,
    weight: 1,
    pairId: "JP-p1",
    category: "daily",
  },
  {
    id: "JP03",
    text: "我習慣把工作切成明確的步驟，並照計畫逐一完成。",
    dimension: "JP",
    direction: 1,
    weight: 1,
    category: "work",
  },
  {
    id: "JP04",
    text: "我常在接近截止日期時才火力全開，而且通常趕得出來。",
    dimension: "JP",
    direction: -1,
    weight: 1,
    category: "work",
  },
  {
    id: "JP05",
    text: "事情懸而未決的時候，我會覺得心裡不太踏實。",
    dimension: "JP",
    direction: 1,
    weight: 1,
    pairId: "JP-p2",
    category: "daily",
  },
  {
    id: "JP06",
    text: "比起早早把事情定下來，保留多一點彈性和選項更讓我自在。",
    dimension: "JP",
    direction: -1,
    weight: 1,
    pairId: "JP-p2",
    category: "daily",
  },
  {
    id: "JP07",
    text: "開始執行之前，我需要先有清楚的目標和時間表。",
    dimension: "JP",
    direction: 1,
    weight: 1,
    category: "work",
  },
  {
    id: "JP08",
    text: "讀書或做專案時，我喜歡同時進行好幾件事，輪流推進。",
    dimension: "JP",
    direction: -1,
    weight: 1,
    category: "learning",
  },
  {
    id: "JP09",
    text: "一旦做了決定，我就不太喜歡再反覆更動。",
    dimension: "JP",
    direction: 1,
    weight: 1,
    category: "decision",
  },
  {
    id: "JP10",
    text: "就算已經決定了，只要出現更好的選項，我隨時願意改變。",
    dimension: "JP",
    direction: -1,
    weight: 1,
    category: "decision",
  },
  {
    id: "JP11",
    text: "行程臨時被打亂時，我需要花一點力氣才能調適過來。",
    dimension: "JP",
    direction: 1,
    weight: 1,
    category: "stress",
  },
  {
    id: "JP12",
    text: "計畫突然改變時，我通常能很快切換，甚至覺得有點新鮮。",
    dimension: "JP",
    direction: -1,
    weight: 1,
    category: "stress",
  },

  // ────────────── A / O：決策推進方式（本站自訂維度） ──────────────
  {
    id: "AO01",
    text: "資訊掌握得差不多時，我就會做出決定，不再拖延。",
    dimension: "AO",
    direction: 1,
    weight: 1,
    pairId: "AO-p1",
    category: "decision",
  },
  {
    id: "AO02",
    text: "就算大方向已經確定，我仍想多比較幾個選項，確認沒有遺漏。",
    dimension: "AO",
    direction: -1,
    weight: 1,
    pairId: "AO-p1",
    category: "decision",
  },
  {
    id: "AO03",
    text: "與其等到方案完美，我寧可先推出一個可用的版本再調整。",
    dimension: "AO",
    direction: 1,
    weight: 1,
    pairId: "AO-p2",
    category: "work",
  },
  {
    id: "AO04",
    text: "重要的成果送出去之前，我會反覆檢查好幾遍。",
    dimension: "AO",
    direction: -1,
    weight: 1,
    pairId: "AO-p2",
    category: "work",
  },
  {
    id: "AO05",
    text: "「想到就做」比「再想想看」更接近我的日常風格。",
    dimension: "AO",
    direction: 1,
    weight: 1,
    category: "daily",
  },
  {
    id: "AO06",
    text: "購買比較貴的東西之前，我會查很多評價和比較資訊。",
    dimension: "AO",
    direction: -1,
    weight: 1,
    category: "daily",
  },
  {
    id: "AO07",
    text: "情況緊急時，我寧願先行動，邊做邊修正。",
    dimension: "AO",
    direction: 1,
    weight: 1,
    category: "stress",
  },
  {
    id: "AO08",
    text: "面對高風險的選擇，我傾向先觀察一陣子再說。",
    dimension: "AO",
    direction: -1,
    weight: 1,
    category: "stress",
  },
  {
    id: "AO09",
    text: "會議拖太久沒有結論時，我會主動推大家做出決定。",
    dimension: "AO",
    direction: 1,
    weight: 1,
    category: "work",
  },
  {
    id: "AO10",
    text: "做完決定之後，我常會再回頭想「還有沒有更好的做法」。",
    dimension: "AO",
    direction: -1,
    weight: 1,
    category: "decision",
  },
  {
    id: "AO11",
    text: "學新工具時，我習慣直接動手試，遇到問題再查資料。",
    dimension: "AO",
    direction: 1,
    weight: 1,
    category: "learning",
  },
  {
    id: "AO12",
    text: "開始嘗試之前，我喜歡先把說明或教學完整看過一遍。",
    dimension: "AO",
    direction: -1,
    weight: 1,
    category: "learning",
  },

  // ────────────── H / C：人際表達溫度（本站自訂維度） ──────────────
  {
    id: "HC01",
    text: "開心或感動的時候，別人從我的表情馬上就看得出來。",
    dimension: "HC",
    direction: 1,
    weight: 1,
    pairId: "HC-p1",
    category: "relationship",
  },
  {
    id: "HC02",
    text: "就算心裡波動很大，我表面上通常還是很平靜。",
    dimension: "HC",
    direction: -1,
    weight: 1,
    pairId: "HC-p1",
    category: "relationship",
  },
  {
    id: "HC03",
    text: "我會很自然地對別人說出讚美和感謝。",
    dimension: "HC",
    direction: 1,
    weight: 1,
    pairId: "HC-p2",
    category: "relationship",
  },
  {
    id: "HC04",
    text: "我欣賞一個人時，常常放在心裡，不太會直接說出口。",
    dimension: "HC",
    direction: -1,
    weight: 1,
    pairId: "HC-p2",
    category: "relationship",
  },
  {
    id: "HC05",
    text: "和熟人相處時，我的情緒起伏會很自然地表現出來。",
    dimension: "HC",
    direction: 1,
    weight: 1,
    category: "daily",
  },
  {
    id: "HC06",
    text: "我習慣和大多數人保持一段舒服的距離。",
    dimension: "HC",
    direction: -1,
    weight: 1,
    category: "daily",
  },
  {
    id: "HC07",
    text: "同事或同學遇到困難時，我會主動表達關心，即使幫不上忙。",
    dimension: "HC",
    direction: 1,
    weight: 1,
    category: "work",
  },
  {
    id: "HC08",
    text: "在職場上，我傾向把互動維持在事情本身，比較少談私人感受。",
    dimension: "HC",
    direction: -1,
    weight: 1,
    category: "work",
  },
  {
    id: "HC09",
    text: "難過的時候，我需要把感受說出來，讓身邊的人知道。",
    dimension: "HC",
    direction: 1,
    weight: 1,
    category: "stress",
  },
  {
    id: "HC10",
    text: "心情不好時，我更希望自己安靜地消化，而不是一直被關心。",
    dimension: "HC",
    direction: -1,
    weight: 1,
    category: "stress",
  },
  {
    id: "HC11",
    text: "初次見面的人常覺得我親切、容易靠近。",
    dimension: "HC",
    direction: 1,
    weight: 1,
    category: "relationship",
  },
  {
    id: "HC12",
    text: "在還不熟的階段，別人可能會覺得我有點難以捉摸。",
    dimension: "HC",
    direction: -1,
    weight: 1,
    category: "relationship",
  },
];

export function getQuestionById(id: string): Question | undefined {
  return QUESTIONS.find((q) => q.id === id);
}

export const QUESTION_IDS = QUESTIONS.map((q) => q.id);
